"""Generate the Portuguese Beamer deck from the canonical English source."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "slides/en/slides.tex"
TARGET = ROOT / "slides/pt/slides.tex"


PHRASES = {
    "From Event Data to Process Insight": "Dos Dados de Eventos aos Insights de Processo",
    "Process Mining": "Mineração de Processos",
    "Institution / Program": "Instituição / Programa",
    "Key idea": "Ideia-chave",
    "Discuss": "Discussão",
    "Course overview": "Visão geral do curso",
    "Course map": "Mapa do curso",
    "What this course is really about": "O que este curso realmente aborda",
    "The learning journey": "A jornada de aprendizagem",
    "Course operating model": "Modelo de funcionamento do curso",
    "Process Thinking and Process Mining": "Pensamento de Processos e Mineração de Processos",
    "Process thinking": "Pensamento de processos",
    "Start with the operational question, not the algorithm.": "Comece pela questão operacional, não pelo algoritmo.",
    "A process is behavior over time": "Um processo é comportamento ao longo do tempo",
    "Four questions, four branches": "Quatro perguntas, quatro ramos",
    "Process mining is not a dashboard": "Mineração de processos não é um painel",
    "Frame a useful analysis": "Estruture uma análise útil",
    "Event Data and Event-Log Semantics": "Dados de Eventos e Semântica do Log de Eventos",
    "Event-log semantics": "Semântica do log de eventos",
    "The quality of the analysis begins with the meaning of an event.": "A qualidade da análise começa pelo significado de um evento.",
    "The minimum viable event log": "O log de eventos mínimo viável",
    "From events to traces and variants": "De eventos a traces e variantes",
    "Lifecycle semantics change the answer": "A semântica do ciclo de vida muda a resposta",
    "A first PM4Py event log": "Um primeiro log de eventos no PM4Py",
    "Event-Log Engineering and Data Quality": "Engenharia de Logs de Eventos e Qualidade de Dados",
    "Event-log engineering": "Engenharia de logs de eventos",
    "An event log is a designed analytical artifact, not a raw database export.": "Um log de eventos é um artefato analítico projetado, não uma exportação bruta do banco de dados.",
    "From source systems to an event log": "Dos sistemas de origem ao log de eventos",
    "Six common data-quality traps": "Seis armadilhas comuns de qualidade de dados",
    "The case-notion test": "O teste da noção de caso",
    "A compact quality report": "Um relatório compacto de qualidade",
    "Profile before you transform": "Faça o profiling antes de transformar",
    "Flattening is a modeling choice": "O flattening é uma escolha de modelagem",
    "Exploratory Process Analysis": "Análise Exploratória de Processos",
    "Exploratory analysis": "Análise exploratória",
    "Build a map of the evidence before building a process model.": "Construa um mapa das evidências antes de construir um modelo de processo.",
    "Explore at four levels": "Explore em quatro níveis",
    "A directly-follows graph": "Um grafo diretamente-seguido",
    "Variants: useful, but easy to misuse": "Variantes: úteis, mas fáceis de usar incorretamente",
    "A variant depends on its trace encoding": "Uma variante depende da codificação do trace",
    "Profile the payload before using it": "Faça o profiling do payload antes de usá-lo",
    "Pareto front for trace-variant detection": "Fronteira de Pareto para detecção de variantes",
    "A modeling-readiness profile": "Um perfil de prontidão para modelagem",
    "PM4Py exploration": "Exploração com PM4Py",
    "Process-Modeling Foundations": "Fundamentos de Modelagem de Processos",
    "Modeling foundations": "Fundamentos de modelagem",
    "Different representations answer different questions.": "Representações diferentes respondem a perguntas diferentes.",
    "Four behavioral building blocks": "Quatro blocos fundamentais de comportamento",
    "A DFG is not a complete process model": "Um DFG não é um modelo de processo completo",
    "Model representations": "Representações de modelos",
    "Choose a modeling strategy": "Escolha uma estratégia de modelagem",
    "Abstraction before algorithm": "Abstração antes do algoritmo",
    "Soundness: can every case finish properly?": "Soundness: todo caso pode terminar corretamente?",
    "Process Discovery": "Descoberta de Processos",
    "Process discovery": "Descoberta de processos",
    "Discovery is a balancing act": "A descoberta exige equilíbrio",
    "Three discovery families": "Três famílias de descoberta",
    "A disciplined discovery experiment": "Um experimento disciplinado de descoberta",
    "Inductive discovery intuition": "Intuição da descoberta indutiva",
    "Discover with PM4Py": "Descoberta com PM4Py",
    "Model Quality and Evaluation": "Qualidade e Avaliação de Modelos",
    "Model quality": "Qualidade do modelo",
    "The four quality dimensions": "As quatro dimensões de qualidade",
    "Build a quality vector, not one score": "Construa um vetor de qualidade, não uma única pontuação",
    "Fitness and precision pull in opposite directions": "Fitness e precisão atuam em direções opostas",
    "Why a weighted average can mislead": "Por que uma média ponderada pode enganar",
    "Pareto dominance and the Pareto front": "Dominância e fronteira de Pareto",
    "Practical Pareto-front selection": "Seleção prática na fronteira de Pareto",
    "Replay and alignments": "Replay e alinhamentos",
    "Evaluate candidates": "Avalie os candidatos",
    "A defensible evaluation protocol": "Um protocolo de avaliação defensável",
    "Conformance Checking": "Verificação de Conformidade",
    "Conformance checking": "Verificação de conformidade",
    "What counts as non-conformance?": "O que conta como não conformidade?",
    "Reading an alignment": "Lendo um alinhamento",
    "From deviations to findings": "Dos desvios aos achados",
    "Alignment diagnostics in PM4Py": "Diagnósticos de alinhamento no PM4Py",
    "Performance and Process Enhancement": "Desempenho e Aprimoramento de Processos",
    "Performance enhancement": "Aprimoramento de processos",
    "Decompose elapsed time": "Decomponha o tempo decorrido",
    "Four bottleneck signatures": "Quatro sinais de gargalo",
    "Compare cohorts, not only averages": "Compare coortes, não apenas médias",
    "From insight to intervention": "Do insight à intervenção",
    "Organizational and Multidimensional Analysis": "Análise Organizacional e Multidimensional",
    "Organizational analysis": "Análise organizacional",
    "A handover-of-work network": "Uma rede de transferência de trabalho",
    "Combine perspectives": "Combine perspectivas",
    "From an event log to machine-learning rows": "Do log de eventos às linhas para aprendizado de máquina",
    "Encoding strategies": "Estratégias de codificação",
    "Feature provenance is part of the model": "A proveniência das features faz parte do modelo",
    "Responsible resource analysis": "Análise responsável de recursos",
    "Correlation is a clue, not a cause": "Correlação é uma pista, não uma causa",
    "Object-Centric Process Mining": "Mineração de Processos Centrada em Objetos",
    "Object-centric mining": "Mineração centrada em objetos",
    "The flattening problem": "O problema do flattening",
    "Object-centric event data": "Dados de eventos centrados em objetos",
    "Case-centric or object-centric?": "Centrado em casos ou em objetos?",
    "Object-centric features without premature flattening": "Features centradas em objetos sem flattening prematuro",
    "Inspect an OCEL with PM4Py": "Inspecione um OCEL com PM4Py",
    "Process-Mining Projects and Communication": "Projetos e Comunicação em Mineração de Processos",
    "Projects and Communication": "Projetos e Comunicação",
    "Projects and communication": "Projetos e comunicação",
    "The project lifecycle": "O ciclo de vida do projeto",
    "Predictive process monitoring tasks": "Tarefas de monitoramento preditivo de processos",
    "Prefixes, labels, and prediction points": "Prefixos, rótulos e pontos de predição",
    "Split by time, group by case": "Separe por tempo e agrupe por caso",
    "Common leakage paths": "Caminhos comuns de vazamento",
    "Evaluate beyond predictive accuracy": "Avalie além da acurácia preditiva",
    "Integration patterns: process mining + ML": "Padrões de integração: mineração de processos + ML",
    "An evidence chain for every finding": "Uma cadeia de evidências para cada achado",
    "Communicate one finding well": "Comunique bem um achado",
    "Reproducibility checklist": "Checklist de reprodutibilidade",
    "Research opportunities": "Oportunidades de pesquisa",
    "Capstone and course close": "Projeto final e encerramento do curso",
    "Capstone": "Projeto final",
    "Capstone: end-to-end process study": "Projeto final: estudo de processo ponta a ponta",
    "Capstone evaluation": "Avaliação do projeto final",
    "The analyst's discipline": "A disciplina do analista",
    "Questions become evidence.": "Perguntas tornam-se evidências.",
    "Evidence becomes better process decisions.": "Evidências tornam-se melhores decisões de processo.",
    "Observe": "Observar",
    "Explain": "Explicar",
    "Improve": "Melhorar",
    "Foundation": "Fundamentos",
    "Application": "Aplicação",
    "Assessment": "Avaliação",
    "Core tools": "Ferramentas principais",
    "Concept checks": "Verificações conceituais",
    "Presentation": "Apresentação",
    "A process consists of:": "Um processo é composto por:",
    "Cases: process instances": "Casos: instâncias do processo",
    "Activities: meaningful steps": "Atividades: etapas significativas",
    "Events: recorded activity executions": "Eventos: execuções registradas de atividades",
    "Resources: people or systems involved": "Recursos: pessoas ou sistemas envolvidos",
    "Outcomes: time, cost, quality,": "Resultados: tempo, custo, qualidade,",
    "What happens?": "O que acontece?",
    "Does it conform?": "Está em conformidade?",
    "How can it improve?": "Como pode melhorar?",
    "What happens next?": "O que acontecerá a seguir?",
    "Discovery": "Descoberta",
    "Conformance": "Conformidade",
    "Enhancement": "Aprimoramento",
    "Predictive Process": "Processo Preditivo",
    "Monitoring": "Monitoramento",
    "Discover": "Descobrir",
    "Check": "Verificar",
    "Enhance": "Aprimorar",
    "Predict": "Prever",
    "Typical analytics": "Análise tradicional",
    "Process mining": "Mineração de processos",
    "Rows and aggregates": "Linhas e agregações",
    "Cases and ordered events": "Casos e eventos ordenados",
    "How many?": "Quantos?",
    "How did work unfold?": "Como o trabalho se desenvolveu?",
    "Usually tabular": "Geralmente tabular",
    "Sequential, concurrent, cyclic": "Sequencial, concorrente, cíclico",
    "KPI or prediction": "KPI ou predição",
    "Behavior, deviation, perfor-": "Comportamento, desvio, desem-",
    "Missed context": "Contexto ignorado",
    "Misleading case/event seman-": "Semântica enganosa de caso/evento",
    "Decision:": "Decisão:",
    "Scope:": "Escopo:",
    "Scope": "Escopo",
    "Case:": "Caso:",
    "Evidence:": "Evidência:",
    "Success:": "Sucesso:",
    "Example": "Exemplo",
    "Case ID": "ID do caso",
    "Activity": "Atividade",
    "Timestamp": "Data/hora",
    "Resource": "Recurso",
    "Amount": "Valor",
    "Trace:": "Trace:",
    "Variant:": "Variante:",
    "Here:": "Aqui:",
    "Start": "Iniciar",
    "Suspend / resume": "Suspender / retomar",
    "Complete": "Concluir",
    "Before running discovery:": "Antes de executar a descoberta:",
    "Extract": "Extrair",
    "and map": "e mapear",
    "Event log": "Log de eventos",
    "Event data": "Dados de eventos",
    "Analysis": "Análise",
    "Mapping decisions include:": "As decisões de mapeamento incluem:",
    "Missing events": "Eventos ausentes",
    "Duplicate events": "Eventos duplicados",
    "Incorrect ordering": "Ordenação incorreta",
    "Mixed granularity": "Granularidade mista",
    "Unstable case identifiers": "Identificadores de caso instáveis",
    "Selection and extraction bias": "Viés de seleção e extração",
    "Diagnostic habit": "Hábito de diagnóstico",
    "Order as case": "Pedido como caso",
    "Item as case": "Item como caso",
    "Check": "Verificação",
    "Evidence": "Evidência",
    "Decision / limitation": "Decisão / limitação",
    "Case completeness": "Completude dos casos",
    "Timestamp order": "Ordenação temporal",
    "Duplicates": "Duplicatas",
    "Activity meaning": "Significado da atividade",
    "Coverage": "Cobertura",
    "Level": "Nível",
    "Profile": "Perfil",
    "Decision it informs": "Decisão que orienta",
    "Event": "Evento",
    "Case": "Caso",
    "Variant": "Variante",
    "Temporal": "Temporal",
    "Flatten by order": "Flattening por pedido",
    "Flatten by item": "Flattening por item",
    "Keep objects": "Manter objetos",
    "Log": "Log",
    "Paths, prevalence, performance": "Caminhos, prevalência, desempenho",
    "Rank": "Posição",
    "Median time": "Tempo mediano",
    "Variants reveal": "As variantes revelam",
    "Variants can hide": "As variantes podem ocultar",
    "Encoding": "Codificação",
    "Trace representation": "Representação do trace",
    "Variants distinguish": "As variantes distinguem",
    "Control-flow": "Fluxo de controle",
    "Lifecycle-aware": "Sensível ao ciclo de vida",
    "Time-aware": "Sensível ao tempo",
    "Payload-aware": "Sensível ao payload",
    "Learned": "Aprendida",
    "Event payload": "Payload do evento",
    "Profile before encoding": "Faça o profiling antes da codificação",
    "Candidate settings": "Configurações candidatas",
    "Objectives": "Objetivos",
    "Deliverable": "Entrega",
    "Interpretation task:": "Tarefa de interpretação:",
    "Sequence": "Sequência",
    "Choice": "Escolha",
    "Parallel": "Paralelo",
    "Loop": "Laço",
    "One follows": "Uma segue",
    "another.": "a outra.",
    "One branch is": "Um ramo é",
    "selected.": "selecionado.",
    "Both occur, order": "Ambas ocorrem; a ordem",
    "varies.": "varia.",
    "Behavior repeats.": "O comportamento se repete.",
    "Purpose": "Finalidade",
    "Strategy": "Estratégia",
    "Representation": "Representação",
    "Emphasize": "Ênfase",
    "Useful strategies": "Estratégias úteis",
    "Practice": "Prática",
    "Raw events": "Eventos brutos",
    "Semantic": "Semântica",
    "mapping": "mapeamento",
    "Activity": "Atividade",
    "abstraction": "abstração",
    "Segment /": "Segmentar /",
    "decompose": "decompor",
    "Candidate cuts:": "Cortes candidatos:",
    "The four quality dimensions": "As quatro dimensões de qualidade",
    "Fitness": "Fitness",
    "Precision": "Precisão",
    "Generalization": "Generalização",
    "Simplicity": "Simplicidade",
    "Dimension": "Dimensão",
    "Example measure": "Exemplo de medida",
    "Interpretation risk": "Risco de interpretação",
    "Stability": "Estabilidade",
    "Feasibility": "Viabilidade",
    "What it hides": "O que ela oculta",
    "Better first step": "Primeiro passo melhor",
    "non-dominated": "não dominado",
    "dominated": "dominado",
    "Candidate settings": "Configurações candidatas",
    "Constrain first": "Primeiro, imponha restrições",
    "Estimate uncertainty": "Estime a incerteza",
    "Inspect sensitivity": "Inspecione a sensibilidade",
    "Review the front": "Revise a fronteira",
    "Select transparently": "Selecione com transparência",
    "Validate once": "Valide uma vez",
    "Token-based replay": "Replay baseado em tokens",
    "Alignments": "Alinhamentos",
    "Candidate models": "Modelos candidatos",
    "What counts as non-conformance?": "O que conta como não conformidade?",
    "Observed trace": "Trace observado",
    "Model path": "Caminho do modelo",
    "Synchronous move": "Movimento síncrono",
    "Move on log": "Movimento no log",
    "Move on model": "Movimento no modelo",
    "Question": "Pergunta",
    "Observation": "Observação",
    "Interpretation": "Interpretação",
    "Validation": "Validação",
    "Action": "Ação",
    "Metric": "Métrica",
    "Service time": "Tempo de serviço",
    "Waiting time": "Tempo de espera",
    "Cycle time": "Tempo de ciclo",
    "Bottleneck": "Gargalo",
    "Cohort": "Coorte",
    "Process mining informs ML": "A mineração de processos informa o ML",
    "ML informs process analysis": "O ML informa a análise de processos",
    "Process": "Processo",
    "model": "modelo",
    "Predictive": "Preditivo",
    "Decision /": "Decisão /",
    "intervention": "intervenção",
    "outcomes": "resultados",
    "context": "contexto",
    "risk": "risco",
    "Required analysis": "Análise obrigatória",
    "Required argument": "Argumentação obrigatória",
    "Evidence of strong work": "Evidência de um trabalho sólido",
    "Question and scope": "Pergunta e escopo",
    "Model quality": "Qualidade do modelo",
    "Prediction": "Predição",
    "Reproducibility": "Reprodutibilidade",
    "Communication": "Comunicação",
}

# Complete teaching statements are translated as units to preserve natural
# Portuguese and avoid mixed-language fragments from word-level substitution.
PHRASES.update({
    "Turn operational records into trustworthy event data.": "Transforme registros operacionais em dados de eventos confiáveis.",
    "Reveal paths, choices, delays, rework, and deviations.": "Revele caminhos, escolhas, atrasos, retrabalho e desvios.",
    "Convert evidence into a testable process intervention.": "Converta evidências em uma intervenção de processo testável.",
    "Process mining connects": "A mineração de processos conecta",
    "The diagram is not the result; the defensible explanation is.": "O diagrama não é o resultado; a explicação defensável é.",
    "Event\\\\data": "Dados de\\\\eventos",
    "Explore": "Explorar",
    "Model": "Modelar",
    "Act": "Agir",
    "Process questions and event semantics": "Questões de processo e semântica de eventos",
    "Data quality and exploratory analysis": "Qualidade de dados e análise exploratória",
    "Behavioral models and discovery": "Modelos comportamentais e descoberta",
    "Model quality and conformance": "Qualidade do modelo e conformidade",
    "Performance and organizational views": "Desempenho e perspectivas organizacionais",
    "Object-centric analysis and delivery": "Análise centrada em objetos e entrega",
    "Each unit combines": "Cada unidade combina",
    "Concepts and visual intuition": "Conceitos e intuição visual",
    "A worked event-log example": "Um exemplo aplicado de log de eventos",
    "A PM4Py laboratory": "Um laboratório com PM4Py",
    "A short interpretation challenge": "Um breve desafio de interpretação",
    "Labs": "Laboratórios",
    "Capstone analysis": "Análise do projeto final",
    "What process do you encounter every week that leaves a digital trace?": "Qual processo você encontra toda semana que deixa um rastro digital?",
    "Receive": "Receber",
    "Review": "Revisar",
    "Approve": "Aprovar",
    "Reject": "Rejeitar",
    "Reveal actual behavior.": "Revele o comportamento real.",
    "Compare log and model.": "Compare o log e o modelo.",
    "Add time, cost, or decisions.": "Adicione tempo, custo ou decisões.",
    "Anticipate outcomes, delays, and risks.": "Antecipe resultados, atrasos e riscos.",
    "Unit": "Unidade",
    "Structure": "Estrutura",
    "Output": "Saída",
    "Risk": "Risco",
    "Behavior, deviation, performance": "Comportamento, desvio, desempenho",
    "Misleading case/event semantics": "Semântica enganosa de caso/evento",
    "A delivery KPI worsened. What sequence-level questions would you ask before recommending a change?": "Um KPI de entrega piorou. Que perguntas sobre a sequência você faria antes de recomendar uma mudança?",
    "What decision should this analysis support?": "Que decisão esta análise deve apoiar?",
    "Where does the process begin and end?": "Onde o processo começa e termina?",
    "What is one process instance?": "O que constitui uma instância do processo?",
    "Which systems record relevant events?": "Quais sistemas registram os eventos relevantes?",
    "Which behavior or outcome should change?": "Qual comportamento ou resultado deve mudar?",
    "Why are some orders late?": "Por que alguns pedidos estão atrasados?",
    "Which paths, handovers, and waiting periods distinguish orders delivered after the five-day target?": "Quais caminhos, transferências e períodos de espera distinguem os pedidos entregues após a meta de cinco dias?",
    "Receive order": "Receber pedido",
    "Check credit": "Verificar crédito",
    "Approve order": "Aprovar pedido",
    "Groups related events.": "Agrupa eventos relacionados.",
    "Names what happened.": "Nomeia o que aconteceu.",
    "Orders events in time.": "Ordena os eventos no tempo.",
    "Resources, costs, lifecycle states, and business attributes enrich analysis, but they do not repair an incoherent case notion.": "Recursos, custos, estados do ciclo de vida e atributos de negócio enriquecem a análise, mas não corrigem uma noção de caso incoerente.",
    "the ordered activity sequence for one case.": "a sequência ordenada de atividades de um caso.",
    "a distinct trace pattern shared by cases.": "um padrão distinto de trace compartilhado por casos.",
    "3 cases, 2 variants.": "3 casos, 2 variantes.",
    "One activity may emit several events": "Uma atividade pode emitir vários eventos",
    "service": "serviço",
    "paused": "pausado",
    "Without lifecycle information, elapsed time may be mistaken for active work time.": "Sem informações do ciclo de vida, o tempo decorrido pode ser confundido com tempo de trabalho ativo.",
    "verify identifiers, timestamps, ordering, duplicates, and event meaning.": "verifique identificadores, datas/horas, ordenação, duplicatas e o significado dos eventos.",
    "Mapping decisions include:": "As decisões de mapeamento incluem:",
    "Which database change counts as a business event?": "Qual alteração no banco de dados conta como evento de negócio?",
    "How are records correlated into cases?": "Como os registros são correlacionados em casos?",
    "Which timestamps and time zones are authoritative?": "Quais datas/horas e fusos horários são oficiais?",
    "Which low-level events should be abstracted?": "Quais eventos de baixo nível devem ser abstraídos?",
    "For every surprising pattern, ask:": "Para cada padrão surpreendente, pergunte:",
    "Is this process behavior, logging behavior, or extraction behavior?": "Isto é comportamento do processo, do registro ou da extração?",
    "A useful case notion should satisfy three questions:": "Uma noção de caso útil deve responder a três perguntas:",
    "Do the grouped events belong to the same process instance?": "Os eventos agrupados pertencem à mesma instância do processo?",
    "Does the resulting sequence have a meaningful beginning and end?": "A sequência resultante possui início e fim significativos?",
    "Does it support the decision the analysis is meant to inform?": "Ela apoia a decisão que a análise pretende orientar?",
    "Good for customer lead time and order completion.": "Adequado para lead time do cliente e conclusão do pedido.",
    "Better for partial fulfillment and item-level handling.": "Melhor para atendimento parcial e tratamento no nível do item.",
    "8.4\\% lack an end event": "8,4\\% não possuem evento final",
    "Exclude open cases from cycle-time KPI": "Excluir casos abertos do KPI de tempo de ciclo",
    "23 negative intervals": "23 intervalos negativos",
    "Correct known clock offset; flag remainder": "Corrigir o desvio conhecido do relógio; sinalizar o restante",
    "1.2\\% exact duplicates": "1,2\\% de duplicatas exatas",
    "Remove with documented key": "Remover com uma chave documentada",
    "has 4 sources": "possui 4 fontes",
    "Split by business semantics": "Separar pela semântica de negócio",
    "Data begins Jan 2025": "Os dados começam em jan. de 2025",
    "No claims about earlier process versions": "Não fazer afirmações sobre versões anteriores do processo",
    "Documenting exclusions is part of the result, not administrative overhead.": "Documentar exclusões faz parte do resultado, não é mera sobrecarga administrativa.",
    "Missingness, duplicates, timestamps": "Valores ausentes, duplicatas, datas/horas",
    "Repair, exclude, or reinterpret": "Corrigir, excluir ou reinterpretar",
    "Length, duration, completeness": "Comprimento, duração, completude",
    "Boundaries and open-case policy": "Limites e política para casos abertos",
    "Frequency, lifecycle, resources": "Frequência, ciclo de vida, recursos",
    "Abstraction and filtering": "Abstração e filtragem",
    "Coverage, rarity, entropy": "Cobertura, raridade, entropia",
    "Noise strategy and segmentation": "Estratégia de ruído e segmentação",
    "Volume, drift, seasonality": "Volume, drift, sazonalidade",
    "Time windows and evaluation split": "Janelas temporais e divisão de avaliação",
    "Profiling is not merely descriptive. It determines which transformations, models, and evaluation designs are defensible.": "O profiling não é apenas descritivo. Ele determina quais transformações, modelos e desenhos de avaliação são defensáveis.",
    "Shared item events converge": "Eventos compartilhados dos itens convergem",
    "Shared order events duplicate": "Eventos compartilhados do pedido são duplicados",
    "Relationships remain explicit": "As relações permanecem explícitas",
    "Which case notion preserves the behavior needed by your question, and which frequencies does it distort?": "Qual noção de caso preserva o comportamento necessário à sua pergunta e quais frequências ela distorce?",
    "Build a map of the evidence before building a process model.": "Construa um mapa das evidências antes de construir um modelo de processo.",
    "Cases, events, date range, coverage": "Casos, eventos, período e cobertura",
    "Duration, event count, outcomes": "Duração, número de eventos e resultados",
    "Frequency, resources, timing": "Frequência, recursos e temporalidade",
    "Which level would reveal rework? Which would reveal a seasonal extraction gap?": "Qual nível revelaria retrabalho? Qual revelaria uma lacuna sazonal de extração?",
    "A DFG summarizes observed adjacency:": "Um DFG resume a adjacência observada:",
    "Nodes are activities; edges mean": "Os nós são atividades; as arestas significam",
    "directly followed by": "diretamente seguido por",
    "Counts can represent frequency or performance": "As contagens podem representar frequência ou desempenho",
    "Loops, choices, and concurrency require careful interpretation": "Laços, escolhas e concorrência exigem interpretação cuidadosa",
    "Dominant routes": "Rotas dominantes",
    "Rework patterns": "Padrões de retrabalho",
    "Exceptional behavior": "Comportamento excepcional",
    "Concurrent behavior": "Comportamento concorrente",
    "Attribute differences": "Diferenças de atributos",
    "Important rare cases": "Casos raros importantes",
    "Routing differences": "Diferenças de roteamento",
    "Activity + transition": "Atividade + transição",
    "Start, suspend, resume, complete": "Início, suspensão, retomada, conclusão",
    "Activity + duration bucket": "Atividade + faixa de duração",
    "Behavioral and timing regimes": "Regimes comportamentais e temporais",
    "Activity + selected attributes": "Atividade + atributos selecionados",
    "Context or outcome cohorts": "Coortes de contexto ou resultado",
    "Sequence / payload embedding": "Embedding de sequência/payload",
    "Similarity beyond exact equality": "Similaridade além da igualdade exata",
    "Variant counts are not properties of the raw log alone. They are produced by an encoding, equivalence rule, and similarity threshold.": "As contagens de variantes não são propriedades apenas do log bruto. Elas são produzidas por uma codificação, uma regra de equivalência e um limiar de similaridade.",
    "Information carried by an event beyond case, activity, and timestamp.": "Informação transportada por um evento além do caso, da atividade e da data/hora.",
    "Structured attributes and measurements": "Atributos estruturados e medições",
    "Text, documents, images, audio, and sensor references": "Texto, documentos, imagens, áudio e referências de sensores",
    "Resource, cost, location, and product context": "Contexto de recurso, custo, localização e produto",
    "Availability at event time": "Disponibilidade no momento do evento",
    "Missingness and cardinality": "Valores ausentes e cardinalidade",
    "Drift, semantics, and cardinality": "Drift, semântica e cardinalidade",
    "Privacy, proxies, and future leakage": "Privacidade, proxies e vazamento de informação futura",
    "Use payload dimensions only when they serve the analytical question; otherwise they can fragment traces into meaningless one-case variants.": "Use dimensões do payload somente quando servirem à pergunta analítica; caso contrário, podem fragmentar traces em variantes sem significado com apenas um caso.",
    "compactness": "compactação",
    "coverage +\\\\relevance": "cobertura +\\\\relevância",
    "exact": "exata",
    "lifecycle": "ciclo de vida",
    "payload": "payload",
    "clustered": "agrupada",
    "dominated settings": "configurações dominadas",
    "Encoding, similarity threshold, rare-variant cutoff, and payload dimensions.": "Codificação, limiar de similaridade, corte de variantes raras e dimensões do payload.",
    "Case coverage, compactness, decision relevance, and temporal stability.": "Cobertura de casos, compactação, relevância para a decisão e estabilidade temporal.",
    "Inspect representative traces before selecting a non-dominated setting.": "Inspecione traces representativos antes de selecionar uma configuração não dominada.",
    "Before discovery or prediction, record:": "Antes da descoberta ou predição, registre:",
    "Case and trace-length distributions": "Distribuições de casos e comprimentos de traces",
    "Variant coverage and long-tail behavior": "Cobertura de variantes e comportamento de cauda longa",
    "Class and outcome imbalance": "Desbalanceamento de classes e resultados",
    "Missing and high-cardinality attributes": "Atributos ausentes e de alta cardinalidade",
    "Process and population drift": "Drift do processo e da população",
    "Open versus completed cases": "Casos abertos versus concluídos",
    "Observation and label timestamps": "Datas/horas de observação e do rótulo",
    "Potential future-information leakage": "Possível vazamento de informação futura",
    "A one-page readiness report: usable population, known distortions, representation choice, split strategy, and excluded information.": "Um relatório de prontidão de uma página: população utilizável, distorções conhecidas, escolha de representação, estratégia de divisão e informações excluídas.",
    "compare common cases with slow cases. Which path differences are plausible explanations, and which need more evidence?": "compare casos comuns com casos lentos. Quais diferenças de caminho são explicações plausíveis e quais exigem mais evidências?",
    "A useful model must distinguish choice from concurrency and permit repetition without permitting everything.": "Um modelo útil deve distinguir escolha de concorrência e permitir repetição sem permitir tudo.",
    "Observed traces": "Traces observados",
    "Evidence suggests": "As evidências sugerem que",
    "may be parallel.": "podem ocorrer em paralelo.",
    "The DFG also appears to allow repeated alternation between": "O DFG também parece permitir alternância repetida entre",
    "That behavior was never observed.": "Esse comportamento nunca foi observado.",
    "Strength": "Ponto forte",
    "Watch for": "Atenção a",
    "Fast, readable overview": "Visão geral rápida e legível",
    "No complete execution semantics": "Sem semântica completa de execução",
    "Structured, sound by construction": "Estruturada e sound por construção",
    "Restricts model shape": "Restringe a forma do modelo",
    "Precise concurrency and replay": "Concorrência e replay precisos",
    "Harder for non-specialists": "Mais difícil para não especialistas",
    "Familiar business notation": "Notação de negócio familiar",
    "Semantics vary by usage": "A semântica varia conforme o uso",
    "State-based behavior": "Comportamento baseado em estados",
    "State explosion": "Explosão de estados",
    "Which representation would you use for stakeholder discussion? Which for alignment-based conformance checking?": "Qual representação você usaria para discutir com stakeholders? E para verificação de conformidade baseada em alinhamentos?",
    "Explain flow": "Explicar o fluxo",
    "Structured discovery": "Descoberta estruturada",
    "Simplicity, fitness": "Simplicidade, fitness",
    "Audit rules": "Auditar regras",
    "Normative modeling": "Modelagem normativa",
    "Soundness, diagnostics": "Soundness, diagnósticos",
    "Explore complexity": "Explorar a complexidade",
    "Frequency-aware discovery": "Descoberta sensível à frequência",
    "Coverage, readability": "Cobertura, legibilidade",
    "Predict state": "Prever o estado",
    "State or prefix model": "Modelo de estado ou prefixo",
    "Transition / features": "Transição/features",
    "Generalization, utility": "Generalização, utilidade",
    "Simplify and annotate": "Simplificar e anotar",
    "Interpretability": "Interpretabilidade",
    "There is no context-free": "Não existe",
    "best model.": "melhor modelo independente do contexto.",
    "State the purpose before selecting the algorithm, representation, and quality criteria.": "Declare a finalidade antes de selecionar o algoritmo, a representação e os critérios de qualidade.",
    "Semantic\\\\mapping": "Mapeamento\\\\semântico",
    "Activity\\\\abstraction": "Abstração de\\\\atividades",
    "Segment /\\\\decompose": "Segmentar /\\\\decompor",
    "Collapse technical events": "Agrupar eventos técnicos",
    "Separate process populations": "Separar populações do processo",
    "Decompose by lifecycle or subprocess": "Decompor por ciclo de vida ou subprocesso",
    "Version every mapping": "Versionar cada mapeamento",
    "Compare before and after profiles": "Comparar perfis antes e depois",
    "Retain a traceable raw-event link": "Manter um vínculo rastreável com o evento bruto",
    "For a workflow model, we usually want:": "Para um modelo de workflow, geralmente desejamos:",
    "One meaningful start and one meaningful completion": "Um início e uma conclusão significativos",
    "Every modeled activity can occur": "Toda atividade modelada pode ocorrer",
    "No deadlocks before completion": "Nenhum deadlock antes da conclusão",
    "No tokens or work left behind after completion": "Nenhum token ou trabalho residual após a conclusão",
    "Why it matters": "Por que isso importa",
    "An attractive diagram can still encode impossible or incomplete behavior.": "Um diagrama atraente ainda pode codificar comportamentos impossíveis ou incompletos.",
    "Formal semantics let us test the model rather than trust its appearance.": "A semântica formal permite testar o modelo em vez de confiar em sua aparência.",
    "Discovery algorithms compress event behavior into an explanatory model.": "Algoritmos de descoberta condensam o comportamento dos eventos em um modelo explicativo.",
    "Underfit": "Subajuste",
    "Useful": "Útil",
    "Overfit": "Sobreajuste",
    "Simple, but allows too much": "Simples, mas permite demais",
    "Explains relevant behavior": "Explica o comportamento relevante",
    "Copies noise and exceptions": "Copia ruído e exceções",
    "Discovery depends on:": "A descoberta depende de:",
    "The event log and its abstraction level": "O log de eventos e seu nível de abstração",
    "The algorithm's behavioral assumptions": "As premissas comportamentais do algoritmo",
    "Noise and frequency thresholds": "Limiares de ruído e frequência",
    "The intended use of the resulting model": "O uso pretendido do modelo resultante",
    "Uses ordering relations to infer causal, parallel, and choice behavior.": "Usa relações de ordenação para inferir comportamentos causais, paralelos e de escolha.",
    "Best as a conceptual foundation.": "Mais indicado como fundamento conceitual.",
    "Uses frequency and dependency measures to tolerate noise.": "Usa medidas de frequência e dependência para tolerar ruído.",
    "Useful for exploratory models.": "Útil para modelos exploratórios.",
    "Recursively finds sequence, choice, parallel, and loop cuts.": "Encontra recursivamente cortes de sequência, escolha, paralelismo e laço.",
    "Produces sound, structured models.": "Produz modelos estruturados e sound.",
    "Temporal or\\\\case split": "Divisão temporal\\\\ou por caso",
    "Algorithm +\\\\parameter grid": "Grade de algoritmo\\\\+ parâmetros",
    "Quality\\\\vector": "Vetor de\\\\qualidade",
    "Stability +\\\\sensitivity": "Estabilidade +\\\\sensibilidade",
    "Shortlist": "Pré-seleção",
    "Define constraints and metric directions before seeing results.": "Defina restrições e direções das métricas antes de ver os resultados.",
    "Keep discovery data separate from final evaluation data.": "Mantenha os dados de descoberta separados dos dados de avaliação final.",
    "Retain all candidate parameters and artifacts, not only the winner.": "Mantenha todos os parâmetros e artefatos candidatos, não apenas o vencedor.",
    "Inspect unstable activities and edges, not only aggregate scores.": "Inspecione atividades e arestas instáveis, não apenas pontuações agregadas.",
    "Find a\\\\behavioral cut": "Encontrar um corte\\\\comportamental",
    "Split log": "Dividir o log",
    "Recurse": "Aplicar recursão",
    "sublogs": "sublogs",
    "Candidate cuts:": "Cortes candidatos:",
    "Exclusive choice": "Escolha exclusiva",
    "The result is a process tree that can be translated into a Petri net or BPMN model.": "O resultado é uma árvore de processos que pode ser traduzida em uma rede de Petri ou modelo BPMN.",
    "Experiment:": "Experimento:",
    "vary the noise threshold. Record which behavior disappears, which remains, and whether the model becomes more useful.": "varie o limiar de ruído. Registre quais comportamentos desaparecem, quais permanecem e se o modelo se torna mais útil.",
    "No single score can tell you whether a model is fit for purpose.": "Nenhuma pontuação isolada informa se um modelo é adequado à sua finalidade.",
    "Can the model replay observed behavior?": "O modelo consegue reproduzir o comportamento observado?",
    "Does it avoid allowing unseen behavior?": "Ele evita permitir comportamentos não observados?",
    "Does it handle plausible future behavior?": "Ele lida com comportamentos futuros plausíveis?",
    "Can people understand and use it?": "As pessoas conseguem compreendê-lo e utilizá-lo?",
    "Perfect fitness is trivial if the model allows every possible trace.": "Fitness perfeito é trivial se o modelo permite todo trace possível.",
    "Quality emerges from the trade-off.": "A qualidade emerge do compromisso entre as dimensões.",
    "Dimension": "Dimensão",
    "Example measure": "Exemplo de medida",
    "Interpretation risk": "Risco de interpretação",
    "Alignment / replay fitness": "Fitness por alinhamento/replay",
    "Rewards permissive models": "Favorece modelos permissivos",
    "Escaping-edge / alignment precision": "Precisão por escaping edges/alinhamento",
    "Sensitive to log coverage": "Sensível à cobertura do log",
    "Holdout replay, cross-validation": "Replay em holdout, validação cruzada",
    "Depends on split design": "Depende do desenho da divisão",
    "Nodes, arcs, control-flow complexity": "Nós, arcos e complexidade do fluxo de controle",
    "Small is not always understandable": "Pequeno nem sempre é compreensível",
    "Bootstrap edge / relation frequency": "Frequência de arestas/relações por bootstrap",
    "Aggregate scores can hide churn": "Pontuações agregadas podem ocultar instabilidade",
    "Soundness, runtime, memory": "Soundness, tempo de execução, memória",
    "Hard constraints, not preferences": "Restrições rígidas, não preferências",
    "Record metric direction, computation method, dataset split, and uncertainty for every component of the quality vector.": "Registre a direção da métrica, o método de cálculo, a divisão dos dados e a incerteza de cada componente do vetor de qualidade.",
    "flower model": "modelo flower",
    "balanced": "equilibrado",
    "trace model": "modelo de traces",
    "The ``best'' point depends on whether the model is for explanation, simulation, compliance, or prediction.": "O ponto ``melhor'' depende de o modelo servir à explicação, simulação, conformidade ou predição.",
    "Suppose:": "Suponha:",
    "What it hides": "O que isso oculta",
    "A critical minimum may be violated": "Um mínimo crítico pode ser violado",
    "Different weights reverse the ranking": "Pesos diferentes invertem o ranking",
    "Compensating metrics may be unacceptable": "Compensar métricas pode ser inaceitável",
    "Scale and normalization alter the result": "Escala e normalização alteram o resultado",
    "Better first step": "Primeiro passo melhor",
    "Apply hard feasibility constraints": "Aplicar restrições rígidas de viabilidade",
    "Remove dominated candidates": "Remover candidatos dominados",
    "Inspect the Pareto front": "Inspecionar a fronteira de Pareto",
    "Add preferences only afterward": "Adicionar preferências somente depois",
    "simplicity": "simplicidade",
    "behavioral\\\\quality": "qualidade\\\\comportamental",
    "knee": "joelho",
    "Candidate": "O candidato",
    "dominates": "domina",
    "when:": "quando:",
    "is no worse on every objective": "não é pior em nenhum objetivo",
    "is better on at least one objective": "é melhor em pelo menos um objetivo",
    "contains candidates not dominated by any other candidate.": "contém candidatos que não são dominados por nenhum outro.",
    "A knee point offers a strong trade-off, but it is a candidate for discussion, not an automatic winner.": "Um ponto de joelho oferece um bom compromisso, mas é candidato à discussão, não um vencedor automático.",
    "require soundness, minimum fitness, and an acceptable runtime or model size.": "exija soundness, fitness mínimo e tempo de execução ou tamanho do modelo aceitável.",
    "bootstrap cases or repeat temporal folds; do not trust tiny score differences.": "faça bootstrap dos casos ou repita folds temporais; não confie em diferenças mínimas de pontuação.",
    "vary thresholds, activity abstraction, and metric implementation.": "varie limiares, abstração de atividades e implementação das métricas.",
    "show all non-dominated models and explain what is gained and lost between adjacent candidates.": "mostre todos os modelos não dominados e explique o que se ganha e perde entre candidatos adjacentes.",
    "use a knee point, lexicographic rule, or stakeholder utility after the front is known.": "use um ponto de joelho, regra lexicográfica ou utilidade dos stakeholders após conhecer a fronteira.",
    "report the final choice on untouched holdout data.": "reporte a escolha final em dados holdout intocados.",
    "Replays traces on a Petri net and counts missing, remaining, consumed, and produced tokens.": "Reproduz traces em uma rede de Petri e conta tokens ausentes, restantes, consumidos e produzidos.",
    "Fast and diagnostic, but can mask some deviations.": "Rápido e diagnóstico, mas pode mascarar alguns desvios.",
    "Find a minimum-cost correspondence between log behavior and model behavior.": "Encontra uma correspondência de custo mínimo entre o comportamento do log e o modelo.",
    "More precise, but computationally more expensive.": "Mais preciso, porém computacionalmente mais caro.",
    "Would you evaluate a compliance model and an exploratory model with the same tolerance for deviations? Why?": "Você avaliaria um modelo de conformidade e um modelo exploratório com a mesma tolerância a desvios? Por quê?",
    "A defensible comparison records:": "Uma comparação defensável registra:",
    "Scores and runtime": "Pontuações e tempo de execução",
    "Model size and readability": "Tamanho e legibilidade do modelo",
    "Training versus held-out performance": "Desempenho em treinamento versus holdout",
    "Which behavior matters to the analytical question": "Qual comportamento importa para a pergunta analítica",
    "Discovery\\\\set": "Conjunto de\\\\descoberta",
    "Validation\\\\set": "Conjunto de\\\\validação",
    "Pareto\\\\shortlist": "Pré-seleção\\\\de Pareto",
    "Domain\\\\review": "Revisão\\\\do domínio",
    "Holdout\\\\test": "Teste\\\\holdout",
    "fit": "ajustar",
    "tune": "selecionar",
    "once": "uma vez",
    "Candidate-generation rules and excluded candidates": "Regras de geração e candidatos excluídos",
    "Full metric vectors with uncertainty, not only the selected model": "Vetores completos de métricas com incerteza, não apenas o modelo selecionado",
    "Pareto-front membership and the final decision rule": "Pertencimento à fronteira de Pareto e regra de decisão final",
    "Holdout performance, known instability, and intended model use": "Desempenho em holdout, instabilidade conhecida e uso pretendido do modelo",
    "Find the smallest meaningful explanation of how reality and the model differ.": "Encontre a menor explicação significativa de como a realidade e o modelo diferem.",
    "The model may be normative": "O modelo pode ser normativo",
    "Policy": "Política",
    "Regulation": "Regulação",
    "Standard operating procedure": "Procedimento operacional padrão",
    "A deviation may indicate risk.": "Um desvio pode indicar risco.",
    "The model may be descriptive": "O modelo pode ser descritivo",
    "Earlier discovery": "Descoberta anterior",
    "Expected operating pattern": "Padrão operacional esperado",
    "Simulation baseline": "Baseline de simulação",
    "A deviation may indicate change.": "Um desvio pode indicar mudança.",
    "Conformance identifies differences. Domain context determines whether those differences are harmful, helpful, or simply missing from the model.": "A conformidade identifica diferenças. O contexto do domínio determina se elas são prejudiciais, úteis ou apenas ausentes do modelo.",
    "Position": "Posição",
    "Move": "Movimento",
    "sync": "síncrono",
    "Event and model agree.": "Evento e modelo concordam.",
    "Observed event not matched.": "Evento observado sem correspondência.",
    "Expected behavior not observed.": "Comportamento esperado não observado.",
    "Locate": "Localize",
    "Which activities, paths, and cases deviate?": "Quais atividades, caminhos e casos apresentam desvios?",
    "Quantify": "Quantifique",
    "How frequent, costly, or delayed are they?": "Quão frequentes, custosos ou atrasados são?",
    "Segment": "Segmente",
    "Which products, teams, or periods differ?": "Quais produtos, equipes ou períodos diferem?",
    "Is the model current and the data complete?": "O modelo está atualizado e os dados estão completos?",
    "What operational mechanism could produce this?": "Qual mecanismo operacional poderia produzir isso?",
    "Strong finding": "Achado sólido",
    "Manual credit review is skipped in 7.3\\% of high-value orders, concentrated in one channel after the April system release.": "A revisão manual de crédito é ignorada em 7,3\\% dos pedidos de alto valor, concentrados em um canal após a versão de abril do sistema.",
    "Lab output:": "Saída do laboratório:",
    "a ranked deviation table containing pattern, affected cases, frequency, performance impact, and a validated interpretation.": "uma tabela ordenada de desvios contendo padrão, casos afetados, frequência, impacto no desempenho e interpretação validada.",
    "A bottleneck is a mechanism, not merely a red number.": "Um gargalo é um mecanismo, não apenas um número vermelho.",
    "Throughput time": "Tempo total de atravessamento",
    "Case start to completion.": "Do início à conclusão do caso.",
    "Time actively worked.": "Tempo de trabalho ativo.",
    "Time between activities.": "Tempo entre atividades.",
    "Long waiting before one activity": "Longa espera antes de uma atividade",
    "Growing queue over time": "Fila crescente ao longo do tempo",
    "Rework returning to the same activity": "Retrabalho retornando à mesma atividade",
    "Excess handovers before completion": "Excesso de transferências antes da conclusão",
    "Do not stop at": "Não pare em",
    "Activity X has the longest average duration.": "A atividade X possui a maior duração média.",
    "Ask whether the delay comes from capacity, batching, policy, missing information, prioritization, or measurement.": "Pergunte se o atraso decorre de capacidade, processamento em lote, política, informação ausente, priorização ou medição.",
    "Median cycle time": "Tempo de ciclo mediano",
    "Rework rate": "Taxa de retrabalho",
    "Standard orders": "Pedidos padrão",
    "Custom orders": "Pedidos personalizados",
    "Custom + partner channel": "Personalizados + canal parceiro",
    "Improvement hypothesis": "Hipótese de melhoria",
    "Partner-channel custom orders arrive with incomplete specifications, triggering clarification loops. A structured intake form should reduce rework and waiting time.": "Pedidos personalizados do canal parceiro chegam com especificações incompletas, gerando ciclos de esclarecimento. Um formulário estruturado de entrada deve reduzir retrabalho e espera.",
    "A hypothesis names a mechanism and predicts a measurable change.": "Uma hipótese nomeia um mecanismo e prevê uma mudança mensurável.",
    "Signal": "Sinal",
    "Candidate\\\\mechanism": "Mecanismo\\\\candidato",
    "Intervention": "Intervenção",
    "Success\\\\metric": "Métrica de\\\\sucesso",
    "Review": "Revisar",
    "Process mining supports improvement by narrowing and testing explanations. It does not establish causality by itself.": "A mineração de processos apoia a melhoria ao restringir e testar explicações. Ela não estabelece causalidade por si só.",
    "Processes are networks of coordination, not only sequences of activities.": "Processos são redes de coordenação, não apenas sequências de atividades.",
    "Sales": "Vendas",
    "Credit": "Crédito",
    "Network analysis can reveal:": "A análise de redes pode revelar:",
    "Frequent handovers and coordination loops": "Transferências frequentes e ciclos de coordenação",
    "Central or overloaded roles": "Papéis centrais ou sobrecarregados",
    "Segregation-of-duties concerns": "Questões de segregação de funções",
    "Differences between formal and actual collaboration": "Diferenças entre a colaboração formal e a real",
    "Control flow": "Fluxo de controle",
    "Which path?": "Qual caminho?",
    "How long?": "Quanto tempo?",
    "Organization": "Organização",
    "Who coordinated?": "Quem coordenou?",
    "Under which conditions?": "Sob quais condições?",
    "Example synthesis": "Exemplo de síntese",
    "Clarification loops are slowest when cases cross from partner sales to central operations, especially for custom products with missing dimensions.": "Os ciclos de esclarecimento são mais lentos quando os casos passam das vendas do parceiro para as operações centrais, especialmente em produtos personalizados com dimensões ausentes.",
    "Case or\\\\prefix": "Caso ou\\\\prefixo",
    "Feature\\\\table": "Tabela de\\\\features",
    "ML model": "Modelo de ML",
    "Case-level row": "Linha no nível do caso",
    "One completed case, usually for retrospective outcome analysis.": "Um caso concluído, geralmente para análise retrospectiva do resultado.",
    "Prefix-level row": "Linha no nível do prefixo",
    "One case observed up to a prediction point, used for online monitoring.": "Um caso observado até um ponto de predição, usado para monitoramento online.",
    "Define the observation cutoff before computing any feature or label.": "Defina o corte de observação antes de calcular qualquer feature ou rótulo.",
    "Representation": "Representação",
    "Main risk": "Risco principal",
    "Aggregation": "Agregação",
    "Counts, durations, last value": "Contagens, durações, último valor",
    "Simple and strong baseline": "Baseline simples e sólido",
    "Loses order": "Perde a ordem",
    "Index-based": "Baseada em índice",
    "Activity/attribute by position": "Atividade/atributo por posição",
    "Preserves early order": "Preserva a ordem inicial",
    "Wide, sparse tables": "Tabelas largas e esparsas",
    "Tokens or learned embeddings": "Tokens ou embeddings aprendidos",
    "Captures order and context": "Captura ordem e contexto",
    "Data and compute demand": "Demanda dados e computação",
    "Process-aware": "Sensível ao processo",
    "Variant, state, alignment moves": "Variante, estado, movimentos de alinhamento",
    "Uses domain structure": "Usa a estrutura do domínio",
    "Model-dependent bias": "Viés dependente do modelo",
    "DFG/object graph features": "Features do DFG/grafo de objetos",
    "Captures relationships": "Captura relações",
    "Complex validation": "Validação complexa",
    "Features by object type": "Features por tipo de objeto",
    "Avoids premature flattening": "Evita flattening prematuro",
    "Aggregation choices remain": "As escolhas de agregação permanecem",
    "Start with an aggregation baseline. Add a richer encoding only when it improves validation utility enough to justify complexity.": "Comece com um baseline de agregação. Adicione uma codificação mais rica somente quando ela melhorar a utilidade na validação o bastante para justificar a complexidade.",
    "For every feature, record:": "Para cada feature, registre:",
    "Source event or object attribute": "Evento de origem ou atributo do objeto",
    "Aggregation and missing-value rule": "Regra de agregação e de valores ausentes",
    "Earliest time at which the feature is available": "Primeiro momento em que a feature está disponível",
    "Case/object population to which it applies": "População de casos/objetos à qual se aplica",
    "Fitted preprocessing parameters and training period": "Parâmetros de pré-processamento ajustados e período de treinamento",
    "Process-aware examples": "Exemplos sensíveis ao processo",
    "Rework count, elapsed time, current activity, variant prefix, alignment cost, model state, handover count, open-object count, and workload at arrival.": "Contagem de retrabalho, tempo decorrido, atividade atual, prefixo da variante, custo de alinhamento, estado do modelo, número de transferências, objetos abertos e carga de trabalho na chegada.",
    "Analyze roles or teams before individuals where possible": "Analise papéis ou equipes antes de indivíduos, quando possível",
    "Check workload, case complexity, and data coverage": "Verifique carga de trabalho, complexidade dos casos e cobertura dos dados",
    "Avoid ranking people using unvalidated process metrics": "Evite ranquear pessoas com métricas de processo não validadas",
    "Distinguish process constraints from individual performance": "Distinga restrições do processo de desempenho individual",
    "Apply access controls, minimization, and purpose limitation": "Aplique controle de acesso, minimização e limitação de finalidade",
    "Event data reflects the system that assigns work. It is rarely a fair standalone measure of an individual's contribution.": "Dados de eventos refletem o sistema que atribui o trabalho. Raramente são uma medida isolada justa da contribuição individual.",
    "A team may appear slower because it receives:": "Uma equipe pode parecer mais lenta porque recebe:",
    "More complex cases": "Casos mais complexos",
    "Cases already delayed upstream": "Casos já atrasados em etapas anteriores",
    "Work with poorer data quality": "Trabalho com dados de menor qualidade",
    "Cases requiring additional controls": "Casos que exigem controles adicionais",
    "What additional data or study design would help distinguish a team effect from case-mix differences?": "Quais dados adicionais ou desenho de estudo ajudariam a distinguir o efeito da equipe das diferenças no perfil dos casos?",
    "Some processes do not have one natural case identifier.": "Alguns processos não possuem um único identificador natural de caso.",
    "One order may contain": "Um pedido pode conter",
    "Several items": "Vários itens",
    "Several deliveries": "Várias entregas",
    "Several invoices": "Várias faturas",
    "One or more payments": "Um ou mais pagamentos",
    "Forced order case": "Caso forçado por pedido",
    "Item-level events may be duplicated across the flattened trace.": "Eventos no nível do item podem ser duplicados no trace achatado.",
    "Forced item case": "Caso forçado por item",
    "Shared invoice and delivery events may be duplicated instead.": "Eventos compartilhados de fatura e entrega podem ser duplicados.",
    "This creates": "Isso cria",
    "convergence": "convergência",
    "divergence": "divergência",
    "misleading frequencies and apparent behavioral relations.": "frequências enganosas e relações comportamentais aparentes.",
    "Order O1": "Pedido O1",
    "Item I1": "Item I1",
    "Package P1": "Pacote P1",
    "Invoice V1": "Fatura V1",
    "represents:": "representa:",
    "Events linked to one or more typed objects": "Eventos ligados a um ou mais objetos tipados",
    "Object-to-object relationships": "Relações entre objetos",
    "Qualified relationships and changing object attributes": "Relações qualificadas e atributos de objetos que mudam",
    "Situation": "Situação",
    "Case-centric": "Centrada em casos",
    "Object-centric": "Centrada em objetos",
    "One stable business instance": "Uma instância de negócio estável",
    "Strong fit": "Muito adequada",
    "Often unnecessary": "Frequentemente desnecessária",
    "Several interacting entities": "Várias entidades interagindo",
    "Distorting": "Distorce",
    "Established KPI by case": "KPI estabelecido por caso",
    "Direct": "Direta",
    "Requires aggregation choices": "Exige escolhas de agregação",
    "Familiar tooling": "Ferramentas familiares",
    "Mature": "Maduras",
    "Emerging": "Emergentes",
    "Relationship questions": "Perguntas sobre relações",
    "Limited": "Limitada",
    "Native": "Nativa",
    "Object-centric analysis does not eliminate modeling choices. It makes relationships explicit so those choices are visible.": "A análise centrada em objetos não elimina escolhas de modelagem. Ela explicita as relações para tornar essas escolhas visíveis.",
    "Per object type": "Por tipo de objeto",
    "Counts and lifecycle states": "Contagens e estados do ciclo de vida",
    "Age and elapsed-time summaries": "Resumos de idade e tempo decorrido",
    "Completed and open related objects": "Objetos relacionados concluídos e abertos",
    "Relationship cardinalities": "Cardinalidades das relações",
    "At prediction time": "No momento da predição",
    "Freeze the object graph at the cutoff": "Congele o grafo de objetos no corte",
    "Aggregate only visible objects": "Agregue somente objetos visíveis",
    "Preserve identifiers for grouped splits": "Preserve identificadores para divisões agrupadas",
    "Test sensitivity to aggregation rules": "Teste a sensibilidade às regras de agregação",
    "Flatten late and explicitly. The target object and prediction time should determine which relationships become features.": "Faça o flattening tarde e explicitamente. O objeto-alvo e o momento da predição devem determinar quais relações se tornam features.",
    "Lab comparison:": "Comparação do laboratório:",
    "flatten the same data by order and by item. Which frequencies or paths become misleading?": "faça o flattening dos mesmos dados por pedido e por item. Quais frequências ou caminhos se tornam enganosos?",
    "A process-mining project succeeds when evidence changes a decision.": "Um projeto de mineração de processos tem sucesso quando a evidência muda uma decisão.",
    "Analyze": "Analisar",
    "Validate": "Validar",
    "refine": "refinar",
    "The lifecycle is iterative. Domain validation may change the event mapping, case notion, model, metric, or even the original question.": "O ciclo de vida é iterativo. A validação do domínio pode alterar o mapeamento de eventos, a noção de caso, o modelo, a métrica ou até a pergunta original.",
    "ML formulation": "Formulação de ML",
    "Example target": "Exemplo de alvo",
    "Useful baseline": "Baseline útil",
    "What happens next?": "O que acontece a seguir?",
    "Classification": "Classificação",
    "Next activity": "Próxima atividade",
    "Most frequent transition": "Transição mais frequente",
    "How long remains?": "Quanto tempo resta?",
    "Regression / survival": "Regressão/sobrevivência",
    "Remaining time": "Tempo restante",
    "Median by current state": "Mediana por estado atual",
    "How will it end?": "Como terminará?",
    "Late / rejected / compliant": "Atraso / rejeição",
    "Base-rate model": "Modelo pela taxa-base",
    "Is this unusual?": "Isto é incomum?",
    "Anomaly detection": "Detecção de anomalias",
    "Deviant prefix": "Prefixo desviante",
    "Frequency / conformance score": "Score de conformidade",
    "The prediction must correspond to an operational decision and a time when someone can still act.": "A predição deve corresponder a uma decisão operacional e a um momento em que alguém ainda possa agir.",
    "observed prefix": "prefixo observado",
    "prediction point": "ponto de predição",
    "future: labels only": "futuro: apenas rótulos",
    "Define": "Defina",
    "Prefix rule and cutoff": "Regra e corte do prefixo",
    "Prediction frequency": "Frequência de predição",
    "Label horizon": "Horizonte do rótulo",
    "Avoid": "Evite",
    "Features computed after cutoff": "Features calculadas após o corte",
    "Labels unavailable in operation": "Rótulos indisponíveis na operação",
    "Duplicated prefixes across splits": "Prefixos duplicados entre divisões",
    "Train": "Treino",
    "Test": "Teste",
    "Assign every case and all its prefixes to exactly one split.": "Atribua cada caso e todos os seus prefixos a exatamente uma divisão.",
    "Fit encoders, imputers, scalers, and vocabularies on training data only.": "Ajuste codificadores, imputadores, escalonadores e vocabulários apenas nos dados de treino.",
    "Prefer temporal evaluation when the deployed model predicts future cases.": "Prefira avaliação temporal quando o modelo implantado prevê casos futuros.",
    "Keep related customers, orders, or objects together when dependence exists.": "Mantenha clientes, pedidos ou objetos relacionados juntos quando houver dependência.",
    "Reserve the test period for one final estimate after tuning.": "Reserve o período de teste para uma estimativa final após a seleção.",
    "Future leakage": "Vazamento do futuro",
    "Final case attributes in a prefix": "Atributos finais do caso em um prefixo",
    "Total event count or final duration": "Número total de eventos ou duração final",
    "Post-outcome resource or status": "Recurso ou status posterior ao resultado",
    "Split leakage": "Vazamento entre divisões",
    "Prefixes from one case in several splits": "Prefixos de um caso em várias divisões",
    "Random event-level splitting": "Divisão aleatória no nível dos eventos",
    "Preprocessing leakage": "Vazamento no pré-processamento",
    "Global normalization or imputation": "Normalização ou imputação global",
    "Variants built from all periods": "Variantes construídas com todos os períodos",
    "Discovery model fitted on test cases": "Modelo de descoberta ajustado nos casos de teste",
    "Operational leakage": "Vazamento operacional",
    "Feature not available at scoring time": "Feature indisponível no momento da pontuação",
    "Label definition changes after deployment": "Definição do rótulo muda após a implantação",
    "Discrimination": "Discriminação",
    "Calibration": "Calibração",
    "Reliability, Brier score, interval coverage": "Confiabilidade, Brier score, cobertura de intervalos",
    "Timeliness": "Antecedência",
    "Earliness, stability across prefixes": "Antecedência, estabilidade entre prefixos",
    "Utility": "Utilidade",
    "Cost, workload, prevented delay, decision value": "Custo, carga de trabalho, atraso evitado, valor da decisão",
    "Also monitor:": "Monitore também:",
    "Performance by cohort and process state": "Desempenho por coorte e estado do processo",
    "Feature, label, and process drift": "Drift de features, rótulos e processo",
    "Alert volume, false-alarm burden, and intervention capacity": "Volume de alertas, carga de falsos alarmes e capacidade de intervenção",
    "Variants, model state, alignments, conformance, rework, and handovers become features or cohorts.": "Variantes, estado do modelo, alinhamentos, conformidade, retrabalho e transferências tornam-se features ou coortes.",
    "Predictions identify risky prefixes and reveal where errors concentrate in the process.": "Predições identificam prefixos de risco e revelam onde os erros se concentram no processo.",
    "Process\\\\model": "Modelo de\\\\processo",
    "Predictive\\\\model": "Modelo\\\\preditivo",
    "Decision /\\\\intervention": "Decisão /\\\\intervenção",
    "Version and monitor the event mapping, process model, encoding, and predictive model as one analytical system.": "Versione e monitore o mapeamento de eventos, o modelo de processo, a codificação e o modelo preditivo como um único sistema analítico.",
    "what decision is at stake?": "qual decisão está em jogo?",
    "what pattern is measured?": "qual padrão foi medido?",
    "what mechanism may explain it?": "qual mecanismo pode explicá-lo?",
    "what did domain experts or other data confirm?": "o que especialistas do domínio ou outros dados confirmaram?",
    "what change should be tested?": "qual mudança deve ser testada?",
    "how will we know whether it worked?": "como saberemos se funcionou?",
    "Separate observation from interpretation. It makes the analysis easier to challenge, improve, and trust.": "Separe observação de interpretação. Isso torna a análise mais fácil de questionar, melhorar e confiar.",
    "Lead with": "Comece por",
    "Operational consequence": "Consequência operacional",
    "Magnitude and affected population": "Magnitude e população afetada",
    "Concise visual evidence": "Evidência visual concisa",
    "Recommended next action": "Próxima ação recomendada",
    "Always include": "Sempre inclua",
    "Data scope": "Escopo dos dados",
    "Key assumptions": "Premissas principais",
    "Uncertainty": "Incerteza",
    "Important alternatives": "Alternativas importantes",
    "Headline pattern": "Padrão de título",
    "What happens": "O que acontece",
    "where": "onde",
    "impact": "impacto",
    "Clarification loops add 4.1 days to partner-channel custom orders.": "Ciclos de esclarecimento adicionam 4,1 dias aos pedidos personalizados do canal parceiro.",
    "Versioned extraction and transformation code": "Código versionado de extração e transformação",
    "Data dictionary and event semantics": "Dicionário de dados e semântica dos eventos",
    "Fixed parameters and package versions": "Parâmetros fixos e versões dos pacotes",
    "Deterministic figures and tables": "Figuras e tabelas determinísticas",
    "Documented exclusions and filters": "Exclusões e filtros documentados",
    "Stored model artifacts": "Artefatos de modelo armazenados",
    "Decision and validation log": "Log de decisões e validações",
    "Privacy-aware sharing strategy": "Estratégia de compartilhamento sensível à privacidade",
    "Could another analyst reproduce your central finding without asking what you clicked?": "Outro analista conseguiria reproduzir seu achado central sem perguntar onde você clicou?",
    "Richer event data": "Dados de eventos mais ricos",
    "Multimodal event logs": "Logs de eventos multimodais",
    "Automated event abstraction": "Abstração automatizada de eventos",
    "Object-centric, streaming, and uncertain events": "Eventos centrados em objetos, em streaming e incertos",
    "Richer analysis": "Análises mais ricas",
    "Multimodal representation learning": "Aprendizado de representações multimodais",
    "Causal process mining": "Mineração causal de processos",
    "Prescriptive monitoring": "Monitoramento prescritivo",
    "Privacy-preserving analytics": "Análises com preservação de privacidade",
    "Align structured events with payload such as free text, documents, images, audio, and sensor streams while preserving time, provenance, and access rules.": "Alinhe eventos estruturados com payloads como texto livre, documentos, imagens, áudio e fluxos de sensores, preservando tempo, proveniência e regras de acesso.",
    "Each modality must add valid, timely, and governable process evidence.": "Cada modalidade deve acrescentar evidência de processo válida, oportuna e governável.",
    "Scope and analytical questions": "Escopo e perguntas analíticas",
    "Event semantics and quality report": "Semântica dos eventos e relatório de qualidade",
    "Representation, flattening, and encoding": "Representação, flattening e codificação",
    "Exploration, performance, and discovery": "Exploração, desempenho e descoberta",
    "Quality vector and Pareto-front comparison": "Vetor de qualidade e comparação pela fronteira de Pareto",
    "Conformance or deviation analysis": "Análise de conformidade ou desvios",
    "One validated finding": "Um achado validado",
    "Predictive baseline when relevant": "Baseline preditivo quando relevante",
    "Leakage-safe split and evaluation": "Divisão e avaliação sem vazamento",
    "One improvement hypothesis": "Uma hipótese de melhoria",
    "Ethical and analytical limitations": "Limitações éticas e analíticas",
    "Reproducible code and artifacts": "Código e artefatos reproduzíveis",
    "Stakeholder-oriented presentation": "Apresentação orientada aos stakeholders",
    "Specific decision, coherent case notion, explicit boundaries": "Decisão específica, noção de caso coerente e limites explícitos",
    "Validated semantics, justified flattening and encoding": "Semântica validada, flattening e codificação justificados",
    "Full metric vectors, Pareto analysis, stable selection rule": "Vetores completos de métricas, análise de Pareto e regra de seleção estável",
    "Leakage-safe split, calibrated errors, operational baseline": "Divisão sem vazamento, erros calibrados e baseline operacional",
    "Findings distinguish evidence from explanation": "Achados distinguem evidência de explicação",
    "Analysis runs from documented inputs to outputs": "A análise executa das entradas documentadas até as saídas",
    "Consequence, uncertainty, and next action are clear": "Consequência, incerteza e próxima ação estão claras",
    "Question the event semantics.": "Questione a semântica dos eventos.",
    "Make representation choices explicit.": "Torne explícitas as escolhas de representação.",
    "Compare quality vectors, not one score.": "Compare vetores de qualidade, não uma única pontuação.",
    "Prevent leakage before training.": "Previna vazamento antes do treinamento.",
    "Turn findings and predictions into testable actions.": "Transforme achados e predições em ações testáveis.",
    "The most important process-mining skill is knowing what the data can support you in saying.": "A habilidade mais importante em mineração de processos é saber o que os dados permitem afirmar.",
    "A process model is a claim about possible behavior. An event log is evidence of observed behavior.": "Um modelo de processo é uma afirmação sobre comportamentos possíveis. Um log de eventos é evidência do comportamento observado.",
    "The \\textbf{Pareto front} contains candidates not dominated by any other candidate.": "A \\textbf{fronteira de Pareto} contém candidatos que não são dominados por nenhum outro.",
    "Activity sequence": "Sequência de atividades",
    "Process tree": "Árvore de processos",
    "Petri net": "Rede de Petri",
    "heuristics net": "rede heurística",
    "Communicate": "Comunicar",
})


WORDS = {
    "and": "e",
    "or": "ou",
    "with": "com",
    "without": "sem",
    "before": "antes",
    "after": "depois",
    "from": "de",
    "to": "para",
    "by": "por",
    "of": "de",
    "for": "para",
    "in": "em",
    "on": "em",
    "between": "entre",
    "against": "contra",
    "through": "por meio de",
    "each": "cada",
    "every": "todo",
    "one": "um",
    "all": "todos",
    "which": "qual",
    "what": "o que",
    "when": "quando",
    "where": "onde",
    "why": "por que",
    "how": "como",
    "data": "dados",
    "quality": "qualidade",
    "process": "processo",
    "model": "modelo",
    "models": "modelos",
    "event": "evento",
    "events": "eventos",
    "activity": "atividade",
    "activities": "atividades",
    "case": "caso",
    "cases": "casos",
    "behavior": "comportamento",
    "analysis": "análise",
    "attributes": "atributos",
    "resources": "recursos",
    "time": "tempo",
    "cost": "custo",
    "performance": "desempenho",
    "frequency": "frequência",
    "outcome": "resultado",
    "outcomes": "resultados",
    "current": "atual",
    "future": "futuro",
    "training": "treinamento",
    "holdout": "holdout",
    "selection": "seleção",
    "threshold": "limiar",
    "candidate": "candidato",
    "candidates": "candidatos",
    "compare": "compare",
    "choose": "escolha",
    "identify": "identifique",
    "record": "registre",
    "report": "relatório",
    "question": "pergunta",
    "finding": "achado",
    "findings": "achados",
    "decision": "decisão",
    "system": "sistema",
    "systems": "sistemas",
    "workflow": "fluxo de trabalho",
    "work": "trabalho",
    "risk": "risco",
    "purpose": "finalidade",
    "complexity": "complexidade",
    "simple": "simples",
    "important": "importante",
    "observed": "observado",
    "possible": "possível",
    "missing": "ausente",
    "rare": "raro",
    "common": "comum",
    "structured": "estruturado",
    "responsible": "responsável",
    "research": "pesquisa",
    "opportunities": "oportunidades",
}

SINGLE_PHRASES = tuple(
    (source, target)
    for source, target in PHRASES.items()
    if " " not in source
)


def translate_phrases(text: str) -> str:
    for source, target in sorted(PHRASES.items(), key=lambda item: len(item[0]), reverse=True):
        if " " not in source:
            continue
        pattern = re.escape(source).replace(r"\ ", r"\s+")
        text = re.sub(
            rf"(?<!\w){pattern}(?!\w)",
            lambda _match, replacement=target: replacement,
            text,
        )
    return text


def translate_line(line: str, in_tikz: bool = False) -> str:
    stripped = line.lstrip()
    if stripped.startswith(r"\usetikzlibrary"):
        return line
    technical = in_tikz or stripped.startswith(
        (
            r"\node",
            r"\draw",
            r"\fill",
            r"\path",
            r"\foreach",
            r"\coordinate",
        )
    )
    if technical:
        def translate_group(match: re.Match[str]) -> str:
            content = match.group(1)
            for source, target in SINGLE_PHRASES:
                content = re.sub(
                    rf"(?<!\w){re.escape(source)}(?!\w)",
                    lambda _match, replacement=target: replacement,
                    content,
                )
            return "{" + content + "}"

        return re.sub(r"\{([^{}]*)\}", translate_group, line)
    for source, target in SINGLE_PHRASES:
        line = re.sub(
            rf"(?<!\w){re.escape(source)}(?!\w)",
            lambda _match, replacement=target: replacement,
            line,
        )
    for source, target in sorted(WORDS.items(), key=lambda item: len(item[0]), reverse=True):
        line = re.sub(rf"\b{re.escape(source)}\b", target, line, flags=re.IGNORECASE)
    return line


def main() -> None:
    source_text = SOURCE.read_text()
    listings: list[str] = []

    def protect_listing(match: re.Match[str]) -> str:
        listings.append(match.group(0))
        return f"@@LISTING_{len(listings) - 1}@@"

    protected = re.sub(
        r"\\begin\{lstlisting\}.*?\\end\{lstlisting\}",
        protect_listing,
        source_text,
        flags=re.DOTALL,
    )
    protected = translate_phrases(protected)
    for index, listing in enumerate(listings):
        protected = protected.replace(f"@@LISTING_{index}@@", listing)

    lines = protected.splitlines(keepends=True)
    translated = []
    in_listing = False
    in_tikz = False
    in_tikzset = False
    for line in lines:
        if r"\begin{lstlisting}" in line:
            in_listing = True
            translated.append(line)
            continue
        if r"\end{lstlisting}" in line:
            in_listing = False
            translated.append(line)
            continue
        if r"\begin{tikzpicture}" in line:
            in_tikz = True
        if r"\tikzset{" in line:
            in_tikzset = True
        translated.append(
            line if in_listing else translate_line(line, in_tikz or in_tikzset)
        )
        if r"\end{tikzpicture}" in line:
            in_tikz = False
        if in_tikzset and line.strip() == "}":
            in_tikzset = False
    output = "".join(translated)
    layout_replacements = {
        r"\setbeamerfont{title}{size=\fontsize{28}{31}\selectfont,series=\bfseries}":
            r"\setbeamerfont{title}{size=\fontsize{24}{27}\selectfont,series=\bfseries}",
        r"\begin{frame}{Mineração de processos não é um painel}":
            r"\begin{frame}[shrink=5]{Mineração de processos não é um painel}",
        r"\begin{frame}{Um relatório compacto de qualidade}":
            r"\begin{frame}[shrink=3]{Um relatório compacto de qualidade}",
        r"\begin{frame}{Faça o profiling antes de transformar}":
            r"\begin{frame}[shrink=8]{Faça o profiling antes de transformar}",
        r"\begin{frame}{O flattening é uma escolha de modelagem}":
            r"\begin{frame}[shrink=2]{O flattening é uma escolha de modelagem}",
        r"\begin{frame}{Uma variante depende da codificação do trace}":
            r"\begin{frame}[shrink=3]{Uma variante depende da codificação do trace}",
        r"\begin{frame}{Um perfil de prontidão para modelagem}":
            r"\begin{frame}[shrink=4]{Um perfil de prontidão para modelagem}",
        r"\begin{frame}{Escolha uma estratégia de modelagem}":
            r"\begin{frame}[shrink=4]{Escolha uma estratégia de modelagem}",
        r"\begin{frame}{Tarefas de monitoramento preditivo de processos}":
            r"\begin{frame}[shrink=6]{Tarefas de monitoramento preditivo de processos}",
        r"\begin{frame}{Oportunidades de pesquisa}":
            r"\begin{frame}[shrink=8]{Oportunidades de pesquisa}",
    }
    for source, target in layout_replacements.items():
        output = output.replace(source, target)
    TARGET.write_text(output)


if __name__ == "__main__":
    main()
